buildscript {
    repositories {
        mavenCentral()
        jcenter()
        maven {
            name = 'forge'
            url = 'https://maven.minecraftforge.net/'
        }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.1-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'

version = '2.3'
group = 'dev.luvia'
archivesBaseName = 'LuviaClient'

sourceCompatibility = 1.8
targetCompatibility = 1.8

minecraft {
    version = '1.8.9-11.15.1.2318-1.8.9'
    mappings = 'stable_22'
    runDir = 'run'
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mcversion', project.minecraft.version

    filesMatching('mcmod.info') {
        expand(
            'version': project.version,
            'mcversion': project.minecraft.version
        )
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
